### ISSUE TITLE
how to play the video source after execute? thank you

### ISSUE THREAD

**Issue by gerwinbryan** [vn33/IndianVehicleLicensePlateDetection-using-Yolov8-and-EasyOCR#1]

**Comment by vn33** [comment]
Hi, I’ve removed the video from the repo due to copyright concerns. Please download any Indian traffic video, update the file path as shown in the image, and the output video will be generated. Thanks

![Screenshot 2024-09-21 210542](https://github.com/user-attachments/assets/f87dda91-948d-449e-9b8e-3ea72761c93e)

**Comment by gerwinbryan** [comment]
yes, but it does not display the video upon running. Results can only be seen in the terminal
